version: "3.8"
services:
  app:
    build: ./infra/php
#    ホスト側の ./backend ディレクトリをappサービスのコンテナ内 /work へマウント
    volumes:
      - ./backend:/work


  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work